# Generated by Django 3.2.8 on 2021-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('userTpye', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userAge', models.IntegerField()),
                ('userGander', models.CharField(max_length=20)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhone', models.IntegerField()),
                ('userDate', models.DateField()),
                ('userTime', models.IntegerField()),
                ('userVac', models.IntegerField()),
                ('userSyp', models.CharField(max_length=20)),
                ('userResult', models.CharField(max_length=20)),
            ],
        ),
    ]
