# Generated by Django 3.2.8 on 2021-10-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0002_auto_20211017_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userAge',
            field=models.IntegerField(max_length=20),
        ),
    ]
