# Generated by Django 3.2.8 on 2021-10-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0004_alter_user_userage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userAge',
            field=models.CharField(max_length=20),
        ),
    ]
